sn:
  twitter:
    url: https://twitter.com/FranceArchives
    title: Follow FranceArchives on Twitter

  youtube:
    url: https://www.youtube.com/channel/UChKZFqPD_Xk82UjCQUtLBrg
    title: Follow FranceArchives on Youtube
